openapi: 3.0.1
info:
  title: STD21014 API
  description: 'Global description of my API'
  version: 1.0.0
servers:
 - url: https://STD21014.com
tags: 
 - name: Film

 - name: Category

 - name: Projection

paths:
 /Film:
    get:
      tags:
        - Film
      operationId: getFilm
      summary: Get all Films
      description: Get all Films with details
      parameters : 
        - name : page
          in : query 
          schema : 
             type : integer
      responses:
        200: 
          description: List of Films
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Film'
        400:
          description: Bad request
    post: 
      tags:
        - Film
      operationId: insertFilm
      summary : Add new Film
      description: add new Film
      requestBody:
        description: Film to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Film'
        required: true
      responses:
        201:
          description: Film added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        400:
          description: Bad request
    put :
      tags :
       - Film
      summary : Update the information of the Film
      description: update the information
      requestBody:
        description : Film updated 
        content : 
          application/json :
            schema :
               $ref: '#/components/schemas/Film'
        required: true
      responses: 
        202: 
          description : Update succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        400: 
          description : Bad request           
      
      
 /Film/{title}: 
    get:
      tags:
        - Film
      summary: Get a Film by title
      operationId: getFilms
      description: Get a Film by title with details
      parameters :
      - name : title
        in : path
        schema :
          type : string
        required: true
      responses:
        200: 
          description : Here's your Film that you choose
          content: 
            application/json:
                schema :
                  type : array
                  items :
                    $ref: '#/components/schemas/Film'
        400 : 
          description: Bad request
        404 : 
          description : Entity not found
    delete :
      tags :
      - Film
      summary : Delete a Film
      operationId: delete
      description : Delete a Film by title
      parameters :
      - name : title
        in : path
        schema :
          type : string
        required: true
      responses :
        200 : 
          description : Delete succesfully
        400 : 
          description : Bad request
        404 : 
          description : Entity not found
    patch: 
      tags: 
        -  Film
      summary: Update information
      operationId: patchFilm
      parameters: 
      - name : title
        in : path
        schema :
          type : string
        required: true  
      requestBody: 
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/Film"
            examples: 
              changeResumé: 
                summary: Change resume
                description: How to change resume and what it does
                value: 
                  title: "Title 1"
                  resumé: "synopsis..."
              
      responses: 
        200: 
          description : Update succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Film'
        400: 
          description : Bad request
 /Films/{categoryName}:
    get : 
      tags : 
        - Film
      summary : Get all Film by category
      description : Get all Film by categpry
      parameters :
      - name : categoryName
        in : path
        schema : 
          type : string
        required : true
      responses : 
        200 : 
          description : Here's all Film in the catégory
          content: 
            application/json: 
              schema: 
                $ref: "#/components/schemas/CategoryFilm"
        400 : 
          description : Bad request
        404 : 
          description : Entity not found
  
 
 /projection:
  get: 
    tags: 
      -  Projection
    operationId: getProjection
    summary : get all projection
    description: get all projection
    responses: 
      200: 
        description: Here's all projection
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/Projection"
      400:
        description: bad request
  post: 
    tags: 
      -  Projection
    summary: Create new projection
    requestBody:
      description: projection to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Projection'
      required: true 
    responses: 
      200: 
        description: Here's all projection
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/Projection"
      400:
        description: bad request
  put:
    tags : 
      - Projection
    summary : Update sprojection
    description : Projection update
    requestBody :
      description : Room updated
      content: 
          application/json :
            schema : 
              $ref : '#/components/schemas/Projection'
      required: true
    responses:
        200 :
          description : Room updated
        400 :
          description : Bad request
  patch: 
    tags: 
      -  Projection
    summary: Update information
    operationId: patchProjection
    requestBody: 
      content: 
        application/json: 
          schema: 
            $ref: "#/components/schemas/Projection"
          examples: 
            changeDate: 
              summary: Change Date
              description: How to change date and what it does
              value: 
                Room: [{"numero": 1}]
                Film: [{"title": "Thor love and thunder"}]
                date: "16 juillet 2022"           
    responses: 
      200: 
        description : Update succesful
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Projection'
      400: 
        description : Bad request
  delete : 
    tags : 
      - Projection
    summary : Delete a projection
    description : Delete a projection by a numero
    parameters : 
      - name : numero
        in : query
        schema: 
          $ref: "#/components/schemas/Projection"
        required : true
    responses :
      200 :
        description : Delete succesfully
      400 : 
        description : Bad request
      404 : 
        description : Entity not found

 /Category:
  get: 
    tags: 
      -  Category
    operationId: getCat
    summary : get all category
    description: get all category
    responses: 
      200: 
        description: Here's all category
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/Category"
      400:
        description: bad request 
        
  post: 
    tags: 
      -  Category
    summary: Create new category
    requestBody:
      description: category to be added
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Category'
      required: true 
    responses: 
      201: 
        description: Here's all projection
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/Category"
      400:
        description: bad request
  delete : 
    tags : 
      - Category
    summary : Delete a catégory
    description : Delete a projection by a numero
    responses :
      200 :
        description : Delete succesfully
        content: 
          application/json: 
            schema: 
              $ref: "#/components/schemas/Category"
      400 : 
        description : Bad request
      404 : 
        description : Entity not found   
  patch: 
    tags: 
      -  Category
    summary: Update information
    operationId: updateCategory
    requestBody: 
      content: 
        application/json: 
          schema: 
            $ref: "#/components/schemas/Category"
          examples: 
            changeDate: 
              summary: Change Date
              description: How to change date and what it does
              value: 
                name: "romantique"           
    responses: 
      200: 
        description : Update succesful
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      400: 
        description : Bad request 

  put:
    tags : 
      - Category
    summary : Update category
    description : Category update
    requestBody :
      description : category updated
      content: 
          application/json :
            schema : 
              $ref : '#/components/schemas/Category'
      required: true
    responses:
        200 :
          description : Room updated
        400 :
          description : Bad request
       
 /Category/{categoryName}:
  delete : 
    tags : 
      - Category
    summary : Delete a projection
    description : Delete a projection by a numero
    parameters : 
      - name : categoryName
        in : path
        schema: 
          type: string
        required : true
    responses :
      200 :
        description : Delete succesfully
      400 : 
        description : Bad request
      404 : 
        description : Entity not found
 /Categories/{title}: 
  get:
    tags:
      - Category
    summary: Get a category by Film title
    operationId: getCategory
    description: Get a category by title with details
    parameters :
    - name : title
      in : path
      schema :
        type : string
        example: 
          title: "Title"
      required: true
    responses:
      200: 
        description : Here's the Film that you choose
        content: 
          application/json:
              schema :
                type : array
                items :
                  $ref: '#/components/schemas/Category'
      400 : 
        description: Bad request
      404 : 
        description : Entity not found
    

components:
  schemas:
    Projection:
      type: object
      properties: 
        Room:
          type: array
          items: 
            $ref: "#/components/schemas/Room"
        Film:
          type: array
          items: 
            $ref: "#/components/schemas/Film"
        date:
          type: string
          example: "15 juillet 2022"
        heure:
          type: string
          example: "19h00"
    Film:
      type: object
      properties: 
        title:
          type: string
          example: "Title 1"
        durée:
          type: string
          example: "2h30"
        dateSortie:
          type: string
          example: "13 juillet 2022"
        realisateur:
          type: string
          example: "realisateur"
        resumé:
          type: string
          example: "synopsis..."
            
    Room:
      type: object
      properties:
        numero:
          type: number
          example: 1
        capacité:
          type: number
          example: 200
          
    CategoryFilm:
      type: object
      properties: 
        name:
          type: string
          example: action
        Film:
          type: array
          items: 
            $ref: "#/components/schemas/Film"
            
    Category:
      type: object
      properties: 
        Category:
          type: string
          example: 
            name: ["action","comédie","romance",...]
        
         
